# Don't print a new line at the start of the prompt
#add_newline = false

# Make in one line
#[line_break]
#disabled = true

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]](bold purple) '
time_format = "%T"
utc_time_offset = "+3"
#time_range = "10:00:00-14:00:00"

#[username]
#style_user = "white bold"
#style_root = "black bold"
#format = "user: [$user]($style) "
#disabled = false
#show_always = true

[hostname]
ssh_only = false
format =  "The [$hostname](bold blue) machine "
trim_at = ".companyname.com"
disabled = false

[character]
#success_symbol = "[âœ](bold green)"   
success_symbol = "[ğŸ‘»ğŸŒ¿ âœ](bold green)"
#success_symbol = "[ğŸŒ€ğŸˆ â† ](bold blue)"
#success_symbol = "[ğŸ¦ğŸ§ â‡¨](bold green)"
#success_symbol = "[ğŸ©ğŸŒ€ â†’](bold blue)"

# Disable the package module, hiding it from the prompt completely
#[package]
#3disabled = true

[java]
symbol = "ğŸŒŸ "
