# Don't print a new line at the start of the prompt
add_newline = false

# Make in one line
[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
#success_symbol = "[âœ](bold green)"   
success_symbol = "[ğŸ‘»ğŸŒ¿ âœ](bold green)"

# Disable the package module, hiding it from the prompt completely
#[package]
#3disabled = true

